apiVersion: apps/v1
kind: Deployment
metadata:
  name: "random-number-gen"
spec:
  selector:
    matchLabels:
      app: "random-number-gen"
  template:
    metadata:
      labels:
        app: "random-number-gen"
    spec:
      containers:
        - name: "random-number-gen"
          image: "docker.io/lehwwmcrnjnhzjaglr/random-number-gen"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "random-number-gen"
spec:
  selector:
    app: "random-number-gen"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080